evaluate:
  type: "shell"
  timeout: 12500
  shell:
    entrypoint: "python3"
    command:
      - "/evaluate.py"
metric:
  type: "shell"
  timeout: 12500
  shell:
    entrypoint: "python3"
    command:
      - "/metric.py"
kubernetesMetricSpecs:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
requireKubernetesMetrics: true
minReplicas: 1
maxReplicas: 30

